let config = {
  address: "localhost",
  port: 8080,
  language: "de",
  logLevel: ["INFO", "LOG", "WARN", "ERROR", "DEBUG"],
  timeFormat: 24,
  units: "metric",
  modules: [
    {
      module: "MMM-PublicTransportHub",
      position: "top_left",
      header: "Reileck · Transitous",
      config: {
        provider: "transitous",
        contact: "KristjanESPERANTO",
        stationId: "de-DELFI_de:15002:5257::01",
        updatesEvery: 60,
        lineStylePreset: "halle",
        maxUnreachableDepartures: 2,
        replaceInDirections: {
          "Halle (Saale), ": "",
          " (Tram/Bus)": "",
          ", Halle (Saale)": "",
        },
        replaceInLineNames: {
          "bus ": "",
          "Bus ": "",
          "STR ": "",
          "Str ": "",
        },
        timeInFutureMinutes: 90,
        includeRelatedStations: true,
      },
    },
    {
      module: "MMM-PublicTransportHub",
      position: "top_right",
      header: "Steintorbrücke · HAFAS (insa)",
      config: {
        provider: "hafas",
        stationId: "8080580",
        hafasProfile: "insa",
        updatesEvery: 60,
        lineStylePreset: "halle",
        showRemarks: false,
        replaceInDirections: {
          "Halle (Saale), ": "",
          " (Tram/Bus)": "",
          ", Halle (Saale)": "",
        },
        replaceInLineNames: {
          "bus ": "",
          "Bus ": "",
          "STR ": "",
          "Str ": "",
        },
        timeInFutureMinutes: 90,
        includeRelatedStations: false,
      },
    },
    {
      module: "MMM-PublicTransportHafas",
      position: "top_center",
      config: {
        hafasProfile: "insa",
        stationID: "8080580",
        stationName: "Steintorbrücke · MMM-PublicTransportHafas · HAFAS (insa)",
        updatesEvery: 60,
        displayLastUpdate: true,
        maxReachableDepartures: 7,
        maxUnreachableDepartures: 0,
        showAbsoluteTime: false,
        timeInFuture: 90,
        customLineStyles: "halle",
        replaceInDirections: {
          "Halle (Saale), ": "",
          " (Tram/Bus)": "",
          ", Halle (Saale)": "",
        },
        showTableHeaders: false,
      },
    },
    {
      module: "MMM-PublicTransportHub",
      position: "bottom_left",
      header: "Berlin Hbf · Transitous",
      config: {
        provider: "transitous",
        contact: "KristjanESPERANTO",
        stationId: "de-DELFI_de:11000:900003201",
        updatesEvery: 60,
        lineStylePreset: "berlin",
        replaceInLineNames: {
          "bus ": "",
          "Bus ": "",
          "STR ": "",
          "Str ": "",
        },
        timeInFutureMinutes: 90,
        includeRelatedStations: false,
      },
    },
    {
      module: "MMM-PublicTransportHub",
      position: "bottom_right",
      header: "Berlin Hbf (S+U) · HAFAS (vbb)",
      config: {
        provider: "hafas",
        stationId: "900003201",
        hafasProfile: "vbb",
        updatesEvery: 60,
        lineStylePreset: "berlin",
        replaceInLineNames: {
          "bus ": "",
          "Bus ": "",
          "STR ": "",
          "Str ": "",
        },
        excludeCanceled: false,
        showRemarks: false,
        timeInFutureMinutes: 90,
        includeRelatedStations: false,
      },
    },
    {
      module: "MMM-PublicTransportHub",
      position: "bottom_center",
      header: "PLK - Warszawa Centralna",
      config: {
        provider: "plk",
        // Request a free key at https://pdp-api.plk-sa.pl/ and put it here.
        apiKey: "YOUR_PLK_API_KEY",
        stationId: "33605",
        updatesEvery: 60,
      },
    },
  ],
}

if (typeof module !== "undefined") {
  module.exports = config
}
